features:
  instant-tnt:
    enabled: true
    # The unit for this variable is meters per second.
    minimum-collision-detonation-speed: 3.2
    explosion:
      power: 2.0
      breaks-blocks: false
      sets-fire: false