features:
  instant-tnt:
    enabled: true
    # The unit for this variable is meters per second.
    minimum-collision-detonation-speed: 0.75
    explosion:
      power: 2.0
      breaks-blocks: false
      sets-fire: false
      spread-radius-blocks: 8.0
      blocks-per-tick-delay: 0.0